### ISSUE TITLE
Look at Report Requirements 

### ISSUE THREAD

**Issue by mroukema** [asweingarten/virtualKeyboard#12]
Let us know the type of information you need and the format you would like it in. 

Also look into requesting resources for the symposium. Some things we will likely want:
Ethernet Drop,
TV/Monitor,
Power

**Comment by s2saba** [comment]
I have added a folder called 'report-requirements' with a markdown file under the TSK repository. This file contains a list of key/value pairs that I need filled in before I can complete the report. I tried to keep it so that you guys have to fill in a minimal amount of information. I will take care of the rest of the research required.

**Comment by s2saba** [comment]
In addition, the report contains a section for requesting equipment. Since I could not find any mention of equipment requests elsewhere on the SVN repository, I presume that is the place for making such requests.
